Adds a folder for the 2023 ECP Tutorial and adds material for DYAD
flux-framework/Tutorials pull request #12
Opened 2023-02-08 19:55 UTC by ilumsden

This PR adds a new folder for the 2023 ECP Tutorial of Flux. This folder contains the same material used in the RADIUSS demo, plus a few extra files for DYAD. More specifically, this PR makes the following changes to the material:

* Adds code to `Dockerfile.spawn` to clone and build DYAD and copy DYAD's demo applications
* Adds code to `Dockerfile.spawn` to build DYAD's demo applications
* Adds a Jupyter Notebook (called `dyad-aws.ipynb`) containing the material for the DYAD demo
* Adds a couple of `.svg` files to be displayed within `dyad-aws.ipynb`

The rest of the material in the new `2023-ECP` directory is the same as the material from the RADIUSS demo.

2023-02-08 22:50 UTC, JaeseungYeom commented on 2023-ECP/JupyterNotebook/README.md
> +docker build -t <desired image name> -f Dockerfile.spawn .
It should clear that <desired image name> here is different from the one above. They are for two different images and thus two different names. We can change it to for example, `<desired_image_name_for_spawner>`

2023-02-08 22:54 UTC, JaeseungYeom commented on 2023-ECP/JupyterNotebook/dyad-aws.ipynb
> +    "## If you are interested in learning more about DYAD, check out our [ReadTheDocs page](https://dyad.readthedocs.io/en/latest/) or [our short paper](https://dyad.readthedocs.io/en/latest/_downloa
Do we have link to the actual code repository?

2023-02-09 05:37 UTC, milroy commented
@ilumsden : I'll review once I test tomorrow, but you'll need to delete `2023-ECP/Flux_RADIUSS_tutorial_2022.pdf`.

2023-02-09 08:28 UTC, milroy requested changes
Repeating in the review: please delete 2023-ECP/Flux_RADIUSS_tutorial_2022.pdf. Apart from renaming two files this looks good.

2023-02-09 08:28 UTC, milroy commented on 2023-ECP/JupyterNotebook/radiuss-aws-flux.ipynb
> +{
Please change the filename to ecp23-flux.ipynb.

2023-02-09 08:28 UTC, milroy commented on 2023-ECP/JupyterNotebook/dyad-aws.ipynb
> +{
A better name for the file might be `ecp23-flux-dyad.ipynb`.

2023-02-09 16:10 UTC, ilumsden commented
@JaeseungYeom @milroy I've made the requested changes.

Also, @JaeseungYeom, I gave a dry run of the DYAD demo in the GCLab group meeting today, and someone recommended some changes to `dyad_example1.svg`. In particular, they recommended:

* Change "P1" and "P2" to something like "Node 1" and "Node 2"
* Change "Task 1", "Task 2", and "Task 3" to use the terms "Producer" and "Consumer"
* Change the background to be clear (the background is white, so it looks a bit odd if you have dark mode enabled in Jupyter)

Not sure if we want to worry about that at this point, but I thought I'd bring it up just in case.

2023-02-09 16:34 UTC, ilumsden commented
I just pushed the figure change stuff.

2023-02-10 00:42 UTC, milroy approved these changes
LGTM! Merging.

2023-02-10 00:42 UTC, merged